### ISSUE TITLE
A mod tried to access the state neighbor table directly

### ISSUE THREAD

**Issue by Pilchh** [malte0811/FerriteCore#102]
Hello,

I am running a modpack on a server but when I try and boot the server, it get the following error:
```
Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config
	at TRANSFORMER/ferritecore@5.0.2/malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101)
	at TRANSFORMER/ferritecore@5.0.2/malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77)
	at TRANSFORMER/canary@0.0.9/com.abdelaziz.canary.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.handler$zmp000$postCreateWithTable(StateHolder.java:528)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.m_61133_(StateHolder.java:1052)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:68)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Block.<init>(Block.java:176)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:39)
```

The full log is here: [https://pastebin.com/xAkYA6mj](https://pastebin.com/xAkYA6mj)

I had a look at some of the other issues as you mentioned disabling `mixin.alloc.blockstate` for Radium. However, it is disabled and I still get this issue. Additionally, by altering the config to enable "populateNeighborTable" it causes errors with a bunch more mods.

Any ideas what I can do?

Thanks

**Comment by malte0811** [comment]
Usually Canary automatically disables the relevant Mixin when FC is present, that doesn't seem to be working here. If disabling `mixin.alloc.blockstate` in the Canary config doesn't help, their whole Mixin plugin may be broken in some way.

You should update Forge. I don't know if it will do anything about this crash, but a few of your mods seem to require a newer Forge version than the one you're using (the "Missing mandatory dependencies" line) and I have no idea if that messes with anything. If that doesn't help, please upload a debug log (`logs/debug.log`) with the new Forge version.

**Comment by Pilchh** [comment]
It did end up being an issue with forge. Thank you for your help.
