### ISSUE TITLE
1.19.2 Forge populateNeighborTable Game Crash

### ISSUE THREAD

**Issue by Forkinmate** [malte0811/FerriteCore#117]
I don't know what is causing the crash, all I know is that it said to set populateNeighborTable to true.

I didn't find any crash-report, but I found this in the minecraft game output which might help

Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config

at TRANSFORMER/ferritecore@5.0.3/malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101)

at TRANSFORMER/ferritecore@5.0.3/malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77)

at TRANSFORMER/radium@0.8.2/me.jellysquid.mods.lithium.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36)

at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.handler$bgi000$postCreateWithTable(StateHolder.java:528)

at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.m_61133_(StateHolder.java:1052)

at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:68)

at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)

at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Block.<init>(Block.java:176)

at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12)

at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:39)

**Comment by malte0811** [comment]
See https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397.
