### ISSUE TITLE
[Forge 1.19.2] A mod tried to access the state neighbor table directly

### ISSUE THREAD

**Issue by Limit-sest** [malte0811/FerriteCore#122]
Hi, in the crash it says to report it on github so that's why i'm here

```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.10/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_224838_(CarverConfiguration.java:20)
	at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:16)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:32)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:21)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236012_(BuiltinRegistries.java:53)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.<clinit>(Registry.java:665)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:110)
	... 13 more
Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config
	at TRANSFORMER/ferritecore@5.0.3/malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101)
	at TRANSFORMER/ferritecore@5.0.3/malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77)
	at TRANSFORMER/radium@0.8.2/me.jellysquid.mods.lithium.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.handler$zkk000$postCreateWithTable(StateHolder.java:528)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.m_61133_(StateHolder.java:1052)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:68)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Block.<init>(Block.java:176)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:39)
```

**Comment by malte0811** [comment]
See https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397.
