### ISSUE TITLE
1.18.2 Startup Crash "Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config"

### ISSUE THREAD

**Issue by xFirefalconx** [malte0811/FerriteCore#124]
Game crashed with Exit Code: 1
No crash report was generated, my latest.log / debug window showed that it got to do with FerriteCore though. Since the mod told me to, I am reporting this bug. (Thanks for including the link)

I am currently working on updates in my Modpack Equine Royals: Petrified Magic. 
Seemingly, **many mods crash after the latest Create Update** (Version 0.5.1.b) which I plugged in in this test run. It could be something else though, I am not totally savant in reading the error log message. 

FerriteCore 4.2.2 (Forge)
Forge 40.2.0
Minecraft 1.18.2
Create 0.5.1.b

I will try to see if the game doesn't crash when enabling this mentioned workaround option. Will comment with the results. Might be a cross mod bug, not sure about that yet. Edit: When I find out it's actually an other mod than Create, I will also comment with the details.

[latest.log](https://github.com/malte0811/FerriteCore/files/11565603/latest.log)

**In case it got cut away, the last few lines I had in my debug window that also led me here:**

13:45:57.309
launcher
main

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:138)
	... 13 more
	Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:633)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.lambda$main$0(Main.java:138)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config
	at TRANSFORMER/ferritecore@4.2.2/malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101)
	at TRANSFORMER/ferritecore@4.2.2/malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77)
	at TRANSFORMER/canary@0.2.1/com.abdelaziz.canary.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.state.StateHolder.handler$cdi000$postCreateWithTable(StateHolder.java:531)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.state.StateHolder.m_61133_(StateHolder.java:1052)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:68)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Block.<init>(Block.java:174)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:40)
	... 18 more
13:45:57.309
monitor
Process Monitor
Process crashed with exit code 1

**Comment by xFirefalconx** [comment]
Update. 
I changed the settings in the config as recommended and also upped the Forge version to 40.2.4 from 40.2.0. The game now opens up. 

What exactly is happening though? I'm a bit intrigued as to what got changed. 


Edit: I reset the config back to false. Game runs. Apparently the Forge version was the issue! Strange.

**Comment by malte0811** [comment]
This looks like a bug in Canary, related to a quirk of Forge (it claims to not be loading any mods while still loading Mixins if some dependency isn't met). In this case it looks like the newer Create build had a higher Forge requirement.
