### ISSUE TITLE
1.20.4 crash on start

### ISSUE THREAD

**Issue by Ilomantis** [malte0811/FerriteCore#140]
As title says, no other mods active.

Minecraft: `1.20.4`
Fabric Loader: `0.15.1`
FerriteCore: `6.0.1`

<details>
<summary>
Log
</summary>

```
[05:39:29] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.1
[05:39:29] [main/INFO]: Loading 5 mods:
        - fabricloader 0.15.1
           \-- mixinextras 0.3.1
        - ferritecore 6.0.1
        - java 21
        - minecraft 1.20.4
[05:39:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:[redacted]/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[05:39:29] [main/INFO]: Compatibility level set to JAVA_17
[05:39:31] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[05:39:32] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'it.unimi.dsi.fastutil.Hash$Strategy net.minecraft.class_156.method_655()'
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.1.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.1.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.1.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.1-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoSuchMethodError: 'it.unimi.dsi.fastutil.Hash$Strategy net.minecraft.class_156.method_655()'
        at malte0811.ferritecore.fastmap.PropertyIndexer.<clinit>(PropertyIndexer.java:26) ~[ferritecore-6.0.1-fabric.jar:?]
        at malte0811.ferritecore.fastmap.FastMapKey.<init>(FastMapKey.java:15) ~[ferritecore-6.0.1-fabric.jar:?]
        at malte0811.ferritecore.fastmap.BinaryFastMapKey.<init>(BinaryFastMapKey.java:16) ~[ferritecore-6.0.1-fabric.jar:?]
        at malte0811.ferritecore.fastmap.FastMap.<init>(FastMap.java:39) ~[ferritecore-6.0.1-fabric.jar:?]
        at malte0811.ferritecore.impl.StateHolderImpl.populateNeighbors(StateHolderImpl.java:41) ~[ferritecore-6.0.1-fabric.jar:?]
        at net.minecraft.class_2688.method_28496(class_2688.java:551) ~[server-intermediary.jar:?]
        at net.minecraft.class_2689.<init>(class_2689.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_2689$class_2690.method_11668(class_2689.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_3611.<init>(class_3611.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_3609.<init>(class_3609.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_3621.<init>(class_3621.java:29) ~[server-intermediary.jar:?]
        at net.minecraft.class_3621$class_3622.<init>(class_3621.java:125) ~[server-intermediary.jar:?]
        at net.minecraft.class_3612.<clinit>(class_3612.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.<init>(class_4970.java:868) ~[server-intermediary.jar:?]
        at net.minecraft.class_2680.<init>(class_2680.java:17) ~[server-intermediary.jar:?]
        at net.minecraft.class_2689.method_28484(class_2689.java:61) ~[server-intermediary.jar:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
        at net.minecraft.class_2689.<init>(class_2689.java:59) ~[server-intermediary.jar:?]
        at net.minecraft.class_2689$class_2690.method_11668(class_2689.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.<init>(class_2248.java:199) ~[server-intermediary.jar:?]
        at net.minecraft.class_2189.<init>(class_2189.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:143) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
        ... 4 more
```

</details>

**Comment by ghost** [comment]
Request: update to 1.20.4

**Comment by malte0811** [comment]
a9a24d4f6945f4e41855f55660915b2f5b570dd7 (should be available on CF and MR once approved)
