### ISSUE TITLE
reporting because told to do so

### ISSUE THREAD

**Issue by sneaxy-den** [malte0811/FerriteCore#145]
Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://g
ithub.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config
        at TRANSFORMER/ferritecore@5.0.3/malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101)
        at TRANSFORMER/ferritecore@5.0.3/malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77)
        at TRANSFORMER/radium@0.8.2/me.jellysquid.mods.lithium.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.handler$zbi000$postCreateWithTable(StateHolder.jav
a:528)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateHolder.m_61133_(StateHolder.java:1552)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:68)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Block.<init>(Block.java:176)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:39)
        ... 25 more
        
You probably need more but I do not know what, i will provide you with additional info when you tell me what the additional info should be :D.

**Comment by malte0811** [comment]
See https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397
