### ISSUE TITLE
A mod tried to access the state neighbor table directly

### ISSUE THREAD

**Issue by 12TROLL14** [malte0811/FerriteCore#152]
The mod asked to report the issue, here is the log :

[17:24:09] [main/WARN] [os.dr.wi.pe.PerfmonDisabled/]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.<init>(BlockBehaviour.java:462)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockState.<init>(BlockState.java:14)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.StateDefinition.m_61057_(StateDefinition.java:61)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:59)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Block.<init>(Block.java:172)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:12)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:45)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:301)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:121)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 12 more
Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config
        at TRANSFORMER/ferritecore@6.0.1/malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101)
        at TRANSFORMER/ferritecore@6.0.1/malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77)
        at TRANSFORMER/canary@0.3.3/com.abdelaziz.canary.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.StateHolder.handler$zdh000$postCreateWithTable(StateHolder.java:531)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.StateHolder.m_61133_(StateHolder.java:1052)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:68)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.StateDefinition$Builder.m_61101_(StateDefinition.java:157)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.material.Fluid.<init>(Fluid.java:32)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.material.FlowingFluid.<init>(FlowingFluid.java:32)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.material.WaterFluid.<init>(WaterFluid.java:29)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.material.WaterFluid$Flowing.<init>(WaterFluid.java:125)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.material.Fluids.<clinit>(Fluids.java:8)
        ... 26 more

**Comment by 12TROLL14** [comment]
Apparently caused by the mod "elytraslot-forge-6.3.0+1.20.1"

**Comment by create-juicey-app** [comment]
same issue over here on my own modpack,

https://pastebin.com/z0gpNR1E
(edit modified so that its in a pastebin and not looking ugly like in github)

Here's the current mods installed
Mods:
  [✔️] [1.19.2]+SecurityCraft+v1.9.6.1.jar
  [✔️] AdChimneys-1.19.2-9.1.19.0-build.1110.jar
  [✔️] AdPother-1.19.2-7.0.20.0-build.1110.jar
  [✔️] appliedenergistics2-forge-12.9.9.jar
  [✔️] Architects-Palette-1.19.2-1.3.5.jar
  [✔️] architectury-6.5.90-forge.jar
  [✔️] architectury-6.6.92-forge.jar
  [✔️] AutoRegLib-1.8.2-55.jar
  [✔️] backpacked-2.1.12-1.19.2.jar
  [✔️] bellsandwhistles-v0.4.4-1.19.2.jar
  [✔️] bellsandwhistles-v0.4.4-1.19.2.zip
  [✔️] bettercombat-forge-1.7.1+1.19.jar
  [✔️] BetterF3-4.0.1-Forge-1.19.2.jar
  [✔️] betterfog-1.19.2-1.1.2.jar
  [✔️] BetterThirdPerson-Forge-1.19-1.9.0.jar
  [✔️] BiomeParticleWeather-v4.0.5-1.19.2-Forge.jar
  [✔️] BiomesOPlenty-1.19.2-17.1.2.544.jar
  [✔️] botarium-forge-1.19.2-1.9.1.jar
  [✔️] BuildingWands-mc1.19.2-2.6.8-release-forge.jar
  [✔️] BuildPasteMod-1.19.2v1.9.5x.jar
  [✔️] camera-forge-1.19.2-1.0.8.jar
  [✔️] catalogue-1.7.0-1.19.2.jar
  [✔️] cccbridge-mc1.19.2-forge-v1.5.1 (1).jar
  [✔️] cc-tweaked-1.19.2-1.101.3.jar
  [✔️] cfm-7.0.0-pre35-1.19.2.jar
  [✔️] cgm-1.3.4-1.19.2.jar
  [✔️] chipped-forge-1.19.2-2.1.5.jar
  [✔️] chisels-and-bits-forge-1.3.146.jar
  [✔️] cloth-config-8.3.103-forge.jar
  [✔️] cloth-config-8.3.115-forge.jar
  [✔️] configured-2.1.1-1.19.2.jar
  [✔️] coroutil-forge-1.19.2-1.3.6.jar
  [✔️] create_misc_and_things_ 1.19.2_4.0A.jar
  [✔️] create-1.19.2-0.5.1.f.jar
  [✔️] createaddition-1.19.2-1.2.3.jar
  [✔️] createbigcannons-forge-1.19.2-0.5.3.b.jar
  [✔️] CreateCasing-1.19.2-1.6.0-ht1.jar
  [✔️] createdieselgenerators-1.19.2-1.2h.jar
  [✔️] create-new-age-forge-1.19.2-1.1.2.jar
  [✔️] CTM-1.19.2-1.1.6+8.jar
  [✔️] Decorative Blocks-forge-1.19.2-3.0.0.jar
  [✔️] do-a-barrel-roll-2.6.2+1.19.2-forge.jar
  [✔️] dynview-1.19.1-2.9.jar
  [✔️] effortlessbuilding-1.19.2-3.5-all.jar
  [✔️] entity_model_features_forge_1.19.2-1.2.3.jar
  [✔️] entity_texture_features_forge_1.19.2-5.2.3.jar
  [✔️] extrasounds-1.2b-1.19.2-forge.jar
  [✔️] FarmersDelight-1.19.2-1.2.4.jar
  [✔️] FastSuite-1.19.2-4.1.1.jar
  [✔️] ferritecore-5.0.3-forge (1).jar
  [✔️] firstaid-1.12.0.jar
  [✔️] ForgeEndertech-1.19.2-10.0.7.0-build.1135 (1).jar
  [✔️] framework-0.4.2-1.19.2.jar
  [✔️] From-The-Fog-1.19-v1.9.1-Forge-Fabric.jar
  [✔️] ftb-chunks-forge-1902.4.4-build.326.jar
  [✔️] ftb-library-forge-1902.4.1-build.236.jar
  [✔️] ftb-teams-forge-1902.2.14-build.123.jar
  [✔️] fusion-1.1.0b-forge-mc1.19.2.jar
  [✔️] iammusicplayer-forge-mc1.19.2-3.19.11.jar
  [✔️] Iceberg-1.19.2-forge-1.1.4.jar
  [✔️] immersive_weathering-1.19.2-1.2.10-forge.jar
  [✔️] interiors-0.5.2+mc1.19.2-FORGE.jar
  [✔️] ItemBorders-1.19.1-1.2.0.jar
  [✔️] kotlinforforge-3.12.0-all.jar
  [✔️] lazydfu-1.19-1.0.2.jar
  [✔️] LegendaryTooltips-1.19.2-forge-1.4.0.jar
  [✔️] mcef-1.2.5.jar
  [✔️] Mekanism-1.19.2-10.3.9.13.jar
  [✔️] MekanismGenerators-1.19.2-10.3.9.13.jar
  [✔️] MOAdecor COOKERY 1.19.2.jar
  [✔️] MOAdecor SCIENCE 1.19.2.jar
  [✔️] moonlight-1.19.2-2.2.43-forge.jar
  [✔️] nifty-1.27.2.jar
  [✔️] notenoughanimations-forge-1.6.2-mc1.19.2.jar
  [✔️] notenoughcrashes-5.0.0+1.19.2-forge.jar
  [✔️] obscure_api-15.jar
  [✔️] oculus-mc1.19.2-1.6.9.jar
  [✔️] OfflineSkins-1.19.2-v1.jar
  [✔️] otyacraftengine-forge-mc1.19.2-3.2.0.jar
  [✔️] out_of_sight-1.19.2-1.0.2.jar
  [✔️] PacketFixer-forge-1.19.2-1.2.8.jar
  [✔️] ParCool-1.19.2-3.0.1.0-R.jar
  [✔️] Patchouli-1.19.2-77.jar
  [✔️] Pehkui-3.7.11+1.19.2-forge.jar
  [✔️] Placebo-1.19.2-7.3.5.jar
  [✔️] player-animation-lib-forge-1.0.2.jar
  [✔️] PresenceFootsteps-1.19.2-1.6.4.1-forge.jar
  [✔️] Prism-1.19.1-1.0.2.jar
  [✔️] Quark-3.4-418.jar
  [✔️] radium-0.8.2.jar
  [✔️] realcamera-1.19.2-forge-0.5.5-beta.jar
  [✔️] rechiseled-1.1.5c-forge-mc1.19.2.jar
  [✔️] rechiseledcreate-1.0.2-forge-mc1.19.jar
  [✔️] red_power-1.1.jar
  [✔️] resourcefullib-forge-1.19.2-1.1.24.jar
  [✔️] rubidium-mc1.19.2-0.6.2c.jar
  [✔️] SereneSeasons-1.19.2-8.1.0.24.jar
  [✔️] simpleplanes-1.19.2-5.2.2.jar
  [✔️] smoothboot(reloaded)-mc1.19.2-0.0.4.jar
  [✔️] sootychimneys-1.19.2-1.2.1.jar
  [✔️] soundphysics-forge-1.19.2-1.0.18.jar
  [✔️] starlight-1.1.1+forge.cf5b10b.jar
  [✔️] Steam_Rails-1.5.3+forge-mc1.19.2.jar
  [✔️] supermartijn642configlib-1.1.8-forge-mc1.19.jar
  [✔️] supermartijn642corelib-1.1.17-forge-mc1.19.2.jar
  [✔️] supplementaries-1.19.2-2.3.20.jar
  [✔️] TerraBlender-forge-1.19.2-2.0.1.166.jar
  [✔️] tia-1.19.2-1.0-forge.jar
  [✔️] Tinted Campfires-1.19.2-1.2.7.jar
  [✔️] ToughAsNails-1.19-8.0.0.78.jar
  [✔️] voicechat-forge-1.19.2-2.4.16.jar
  [✔️] watut-forge-1.19.2-1.0.14.jar
  [✔️] webdisplays-1.3.3 (1).jar
  [✔️] Weeping-Angels-43.0.9-forge.jar
  [✔️] xlpackets-1.0.4-1.19.4.jar
  [✔️] XyCraft Core-0.5.17.jar

Im just gonna enable populateNeighborTable for now

**Comment by malte0811** [comment]
See https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1278544397 and https://github.com/malte0811/FerriteCore/issues/96#issuecomment-1870259336
