### ISSUE TITLE
Massive log spam 'Failed to modify unbaked model'

### ISSUE THREAD

**Issue by mpustovoi** [malte0811/FerriteCore#171]
I have a custom modpack on `Forge 1.20.1` with a ton of mods.

The game starts and works fine, but there is a massive log spam of 'Failed to modify unbaked model' error by `PuzzlesLib`.

I suppose it's some kind of compatibility issue.
The problem appeared maybe about half a month ago.
This makes logging difficult, since there are about 200-280 thousand lines with the same error in the `latest.log`.

The author of the `PuzzlesLib` mod [assumes](https://github.com/Fuzss/puzzleslib/issues/133#issuecomment-2351607445) that the problem isn't with his mod, since the game works fine without `FerriteCore`.

**Comment by malte0811** [comment]
Does this happen with just FerriteCore, PuzzlesLib and DiagonalBlocks? Also, does it still happen when you have your "ton of mods" installed, but remove FerriteCore? If the answer to both of those is no: Can you send me a full modlist of your pack? "A ton of mods" is not enough for me to be able to debug this. It looks like for some reason PuzzlesLib/DiagonalBlocks are trying to set a blockstate property that expects some enum (direction etc) to a boolean. So either they've got a bug in their property selection logic or I have a bug in my property code somewhere.

**Comment by mpustovoi** [comment]
> Does this happen with just FerriteCore, PuzzlesLib and DiagonalBlocks? Also, does it still happen when you have your "ton of mods" installed, but remove FerriteCore?

I'll test it right now.

**Comment by mpustovoi** [comment]
> just FerriteCore, PuzzlesLib and DiagonalBlocks

Here I have a slightly different error `ModelBakery`, which is also very much: https://mclo.gs/hfYVr2j#L3. FerriteCore isn't mentioned here.
At the same time, the error remains without FerriteCore. So I guess I should go back to the issue in PuzzlesLib.

**Comment by mpustovoi** [comment]
> "ton of mods" installed, but remove FerriteCore

Minecraft took 2-3 times longer to run, and I even received a warning from ModernFix that FerriteCore isn't installed.
The length of the log file has grown to 1.3 million lines.
It's full of errors with apparently every wall block and its states. First error as an example:
```log
[<time>] [Worker-ResourceReload-2/ERROR] [Puzzles Lib/]: Failed to modify unbaked model
java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=east, clazz=class net.minecraft.world.level.block.state.properties.WallSide, values=[none, low, tall]} to true on Block{deeperdarker:sculk_grime_brick_wall}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:130) ~[client-1.20.1-20230612.114412-srg.jar%231000!/:?]
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.setBlockStateValue(MultiPartTranslator.java:59) ~[diagonalblocks-forge-8.0.5.jar%231232!/:8.0.5]
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.convertBlockState(MultiPartTranslator.java:50) ~[diagonalblocks-forge-8.0.5.jar%231232!/:8.0.5]
	at fuzs.diagonalblocks.api.v2.client.MultiPartTranslator.convertAnyBlockState(MultiPartTranslator.java:43) ~[diagonalblocks-forge-8.0.5.jar%231232!/:8.0.5]
	at fuzs.diagonalblocks.client.handler.DiagonalModelHandler.onModifyUnbakedModel(DiagonalModelHandler.java:53) ~[diagonalblocks-forge-8.0.5.jar%231232!/:8.0.5]
	at fuzs.puzzleslib.impl.client.event.ForgeClientEventInvokers.lambda$registerLoadingHandlers$6(ForgeClientEventInvokers.java:80) ~[PuzzlesLib-v8.1.23-1.20.1-Forge.jar%23873!/:8.1.23]
	at fuzs.puzzleslib.api.event.v1.core.ForgeEventInvokerRegistry.lambda$register$0(ForgeEventInvokerRegistry.java:25) ~[PuzzlesLib-v8.1.23-1.20.1-Forge.jar%23873!/:8.1.23]
	at fuzs.puzzleslib.impl.event.ForgeEventInvokerRegistryImpl$ForgeEventInvoker.lambda$register$1(ForgeEventInvokerRegistryImpl.java:725) ~[PuzzlesLib-v8.1.23-1.20.1-Forge.jar%23873!/:8.1.23]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23128!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23128!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23128!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23128!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.3.7.jar%231002!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.client.ForgeHooksClient.mdfe4e85$modernfix$lambda$postNamespacedKeySetEvent$0$0(ForgeHooksClient.java:1372) ~[forge-1.20.1-47.3.7-universal.jar%231005!/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:223) ~[fmlcore-1.20.1-47.3.7.jar%231001!/:?]
	at net.minecraftforge.client.ForgeHooksClient.redirect$zfl000$modernfix$postNamespacedKeySetEvent(ForgeHooksClient.java:1367) ~[forge-1.20.1-47.3.7-universal.jar%231005!/:?]
	at net.minecraftforge.client.ForgeHooksClient.onModifyBakingResult(ForgeHooksClient.java:471) ~[forge-1.20.1-47.3.7-universal.jar%231005!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_245476_(ModelManager.java:174) ~[client-1.20.1-20230612.114412-srg.jar%231000!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_246937_(ModelManager.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231000!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
I can't even send it without compression because of the 160 MB size.
[2024-09-15-1.log.gz](https://github.com/user-attachments/files/17006322/2024-09-15-1.log.gz)

Although, I don't have such lines here:
```log
[<time>] [Worker-ResourceReload-0/ERROR] [Puzzles Lib/]: Failed to modify unbaked model
java.lang.ClassCastException: null
```

**Comment by malte0811** [comment]
Ok, then the logspam is a DiagonalBlocks issue. It's not great that FC is throwing a far less detailed error in this case, but that has far lower priority.

**Comment by mpustovoi** [comment]
Yes, I should have guessed, because I forgot an important thing. 
In the test world of my modpack, chunks with diagonal blocks couldn't load at all. Instead, there were only LODs of Distant Horizons, which don't have diagonal blocks.
