### ISSUE TITLE
Crashing server with Ticking Entity

### ISSUE THREAD

**Issue by Neubulae** [malte0811/FerriteCore#21]
```
[21:10:22] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:334) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cjb000$modifiedRunLoop(MinecraftServer.java:5893) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class malte0811.ferritecore.fastmap.immutable.FastMapEntryImmutableMap does not define or inherit an implementation of the resolved method 'abstract com.google.common.collect.ImmutableSet createKeySet()' of abstract class com.google.common.collect.ImmutableMap.
	at com.google.common.collect.ImmutableMap.keySet(ImmutableMap.java:728) ~[Geyser-Fabric-1.4.0-SNAPSHOT.jar:?]
	at net.minecraft.class_2688.method_28501(class_2688.java:88) ~[intermediary-server.jar:?]
	at net.minecraft.class_2384.method_36364(class_2384.java:78) ~[intermediary-server.jar:?]
	at java.util.Map.computeIfAbsent(Map.java:1004) ~[?:?]
	at net.minecraft.class_2384.method_36363(class_2384.java:76) ~[intermediary-server.jar:?]
	at net.minecraft.class_2384.method_36366(class_2384.java:68) ~[intermediary-server.jar:?]
	at net.minecraft.class_1614$class_1615.method_6269(class_1614.java:256) ~[intermediary-server.jar:?]
	at net.minecraft.class_4135.method_6269(class_4135.java:41) ~[intermediary-server.jar:?]
	at net.minecraft.class_1355.startGoals(class_1355.java:644) ~[intermediary-server.jar:?]
	at net.minecraft.class_1355.updateGoalStates(class_1355.java:576) ~[intermediary-server.jar:?]
	at net.minecraft.class_1355.method_6275(class_1355.java:555) ~[intermediary-server.jar:?]
	at net.minecraft.class_1308.method_6023(class_1308.java:732) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2597) ~[intermediary-server.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:538) ~[intermediary-server.jar:?]
	at net.minecraft.class_1588.method_6007(class_1588.java:43) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2342) ~[intermediary-server.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:338) ~[intermediary-server.jar:?]
	at net.minecraft.class_1614.method_5773(class_1614.java:115) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:656) ~[intermediary-server.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:3085) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:418) ~[intermediary-server.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:393) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.redirect$bfk000$ficUpdateSuppressionCrashTick(MinecraftServer.java:2275) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893) ~[intermediary-server.jar:?]
	... 6 more
```
[mods.txt](https://github.com/malte0811/FerriteCore/files/6761252/mods.txt)
modlist

**Comment by malte0811** [comment]
I'll blame this on Geyser for now. They're shipping a newer version of Guava collections, which does not work correctly with the hacks I'm using in that area. This sort of issue isn't new for them (see https://github.com/CardboardPowered/cardboard/issues/139). I can look into adding a workaround for this, but I can't promise anything and it's pretty low priority.

cc @Camotoy

**Comment by Neubulae** [comment]
Got it, it's fine <3

**Comment by Camotoy** [comment]
I'll make sure this gets fixed soon. Thanks!

**Comment by Camotoy** [comment]
Should be resolved by https://github.com/GeyserMC/Geyser-Fabric/commit/6a5691d6bcc04113e357d95ba789678d179c90bb, though untested with this mod.

**Comment by malte0811** [comment]
Thanks, I'll close this then.
