### ISSUE TITLE
Sodium, Lithium, Sodium Extra, Starlight and LambDynamicLights crashes game

### ISSUE THREAD

**Issue by KingCreeperz** [malte0811/FerriteCore#68]
Crash:

error: [2022-03-27T20:55:01Z INFO  rust_launcher::start] Loading version
[2022-03-27T20:55:01Z INFO  rust_launcher::start] Moving mods
info: {"versionSize":220125530,"state":{"VersionLoading":true},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":0}
error: [2022-03-27T20:55:01Z INFO  rust_launcher::start] Finished moving mods
error: [2022-03-27T20:55:01Z INFO  rust_launcher::start] Finished loading version
[2022-03-27T20:55:01Z INFO  rust_launcher::start] Preparing assets
[2022-03-27T20:55:01Z INFO  rust_launcher::start] Preparing JRE
info: {"versionSize":220125530,"state":{"Downloading":["Mods","Jre","Libraries","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":40369}
error: [2022-03-27T20:55:02Z INFO  rust_launcher::start] Preparing libraries
info: {"versionSize":220125530,"state":{"Downloading":["Mods","Libraries","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":18468469}
error: [2022-03-27T20:55:02Z INFO  rust_launcher::start] Preparing mods
error: [2022-03-27T20:55:02Z INFO  rust_launcher::start] Finished preparing mods
info: {"versionSize":220125530,"state":{"Downloading":["Libraries","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":116206195}
info: {"versionSize":220125530,"state":{"Downloading":["Libraries","Assets"]},"currentDownloadRate":41428,"eta":"11 minutes","expectedTasks":6,"downloadSpeed":41428,"downloaded":192654841}
error: [2022-03-27T20:55:03Z INFO  rust_launcher::start] Finished preparing libraries
info: {"versionSize":220125530,"state":{"Downloading":["Assets"]},"currentDownloadRate":41428,"eta":"about 2 hours","expectedTasks":6,"downloadSpeed":41428,"downloaded":464704910}
info: {"versionSize":220125530,"state":{"Downloading":["Assets"]},"currentDownloadRate":4643125,"eta":"less than a minute","expectedTasks":6,"downloadSpeed":4643125,"downloaded":480928953}
error: [2022-03-27T20:55:03Z INFO  rust_launcher::start] Finished preparing assets
info: {"versionSize":220125530,"state":{"Jvm":true},"currentDownloadRate":4643125,"eta":"1 minute","expectedTasks":6,"downloadSpeed":4643125,"downloaded":579603848}
error: [2022-03-27T20:55:03Z INFO  rust_launcher::common::launch] starting JVM with arguments: ["-Djava.library.path=libraries/native\\net/digitalingot/fcef-windows/0.0.1\\extracted/;libraries/native\\net/digitalingot/fwebp-windows/0.0.1\\extracted/;libraries/native\\de/jcm/discord-game-sdk4j-windows/0.5.4\\extracted/;libraries/native\\org/jitsi/jnopus/1.0\\extracted/;libraries/native\\org/lwjgl/lwjgl/3.2.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-jemalloc/3.2.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-openal/3.2.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-opengl/3.2.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-glfw/3.2.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-tinyfd/3.2.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-stb/3.2.2\\extracted/;libraries/native\\com/mojang/text2speech/1.11.3\\extracted/;jre\\jdk17u12-windows-x64\\bin/", "--illegal-access=deny", "--add-opens=java.desktop/java.awt.event=ALL-UNNAMED", "--add-opens=java.desktop/java.awt.color=ALL-UNNAMED", "--add-opens=java.desktop/java.awt=ALL-UNNAMED", "--add-opens=java.base/java.lang=ALL-UNNAMED", "-Xms2048M", "-Xmx2048M", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseG1GC", "-XX:G1NewSizePercent=20", "-XX:G1ReservePercent=20", "-XX:MaxGCPauseMillis=50", "-XX:G1HeapRegionSize=32M", "-Dlog4j2.formatMsgNoLookups=true", "-XX:ErrorFile=feather/java_error.log", "-Djavax.accessibility.assistive_technologies=", "-cp", "libraries\\java\\net/minecraft/client/1.18.1/minecraft-1.18.1.jar;libraries\\java\\net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar;libraries\\java\\net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar;libraries\\java\\net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar;libraries\\java\\net/fabricmc/access-widener/2.0.1/access-widener-2.0.1.jar;libraries\\java\\org/ow2/asm/asm/9.2/asm-9.2.jar;libraries\\java\\org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar;libraries\\java\\org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar;libraries\\java\\org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar;libraries\\java\\org/ow2/asm/asm-util/9.2/asm-util-9.2.jar;libraries\\java\\net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar;libraries\\java\\net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar;libraries\\java\\de/javagl/obj/0.3.0/obj-0.3.0.jar;libraries\\java\\de/jcm/discord-game-sdk4j/0.5.4/discord-game-sdk4j-0.5.4;libraries\\java\\net/digitalingot/feather-server-api-proto/1.0-SNAPSHOT/feather-server-api-proto-1.0-SNAPSHOT.jar;libraries\\java\\net/digitalingot/rust-extension/1.0.7/rust-extension-1.0.7.jar;libraries\\java\\net/digitalingot/fcef/0.0.1/fcef-0.0.1.jar;libraries\\java\\net/digitalingot/fwebp/0.0.1/fwebp-0.0.1.jar;libraries\\java\\org/jitsi/libjitsi/1.0-CUSTOM/libjitsi-1.0-CUSTOM.jar;libraries\\java\\org/jitsi/jitsi-utils/1.0-45-gc3afb76/jitsi-utils-1.0-45-gc3afb76.jar;libraries\\java\\org/capnproto/runtime/0.1.10/runtime-0.1.10.jar;libraries\\java\\javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar;libraries\\java\\com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar;libraries\\java\\com/mojang/patchy/2.1.6/patchy-2.1.6.jar;libraries\\java\\com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar;libraries\\java\\net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar;libraries\\java\\net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar;libraries\\java\\org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar;libraries\\java\\org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar;libraries\\java\\com/ibm/icu/icu4j/69.1/icu4j-69.1.jar;libraries\\java\\com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar;libraries\\java\\net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar;libraries\\java\\io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar;libraries\\java\\com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar;libraries\\java\\com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar;libraries\\java\\org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar;libraries\\java\\commons-io/commons-io/2.11.0/commons-io-2.11.0.jar;libraries\\java\\commons-codec/commons-codec/1.15/commons-codec-1.15.jar;libraries\\java\\com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar;libraries\\java\\com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar;libraries\\java\\com/google/code/gson/gson/2.8.8/gson-2.8.8.jar;libraries\\java\\com/mojang/authlib/3.2.38/authlib-3.2.38.jar;libraries\\java\\org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar;libraries\\java\\org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar;libraries\\java\\commons-logging/commons-logging/1.2/commons-logging-1.2.jar;libraries\\java\\org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar;libraries\\java\\it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar;libraries\\java\\org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar;libraries\\java\\org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar;libraries\\java\\org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar;libraries\\java\\org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar;libraries\\java\\com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar;libraries\\java\\com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar", "net.digitalingot.rustextension.ProxiedStart", "net.fabricmc.loader.launch.knot.KnotClient", "--username", "King_Creeperz", "--version", "1.18.1-feather", "--gameDir", "C:\\Users\\user\\AppData\\Roaming/.minecraft", "--assetsDir", "assets", "--assetIndex", "1.18-feather-game", "--uuid", "8d1ee1e1b0134210a523c96d24fa96b1", "--accessToken", "eyJhbGciOiJIUzI1NiJ9.eyJ4dWlkIjoiMjUzNTQ0NTU3NzcxNTI0NSIsImFnZyI6IkFkdWx0Iiwic3ViIjoiYTg1M2JkYTUtNGZlNS00OWE0LWFhNDEtODRmNDI5MDRhOTA3IiwibmJmIjoxNjQ4NDAwMTI0LCJhdXRoIjoiWEJPWCIsInJvbGVzIjpbXSwiaXNzIjoiYXV0aGVudGljYXRpb24iLCJleHAiOjE2NDg0ODY1MjQsImlhdCI6MTY0ODQwMDEyNCwicGxhdGZvcm0iOiJVTktOT1dOIiwieXVpZCI6IjUxMDQ1Y2VlNWEwM2YzNzYwMTRiZWY4NzY1ZTBlYjFkIn0.pZ1L298S-fNcMHO6xyok7TuO-CfBDAmVqhzy0SjF7As", "--userType", "mojang", "--versionType", "feather"]
info: sending javaw pid
info: starting cleanup
error: OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
info: [15:55:04] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
info: [15:55:04] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
info: [15:55:04] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.3.8 recommends version 1.2.3 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.2.3 or later of reeses-sodium-options for the optimal experience.
info: [15:55:04] [main/INFO]: Loading 71 mods:
	- balm-fabric 2.4.0+0
	- caffeineconfig 1.0.0 via sodium-extra
	- citresewn 0.9.1+1.18.1
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- entityculling 1.5.0
	- fabric 0.46.4+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric
	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric
	- fabricloader 0.13.3
	- feather 1.0.0-SNAPSHOT
	- ferritecore 4.0.0
	- iris 1.2.0-pre
	- java 17
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- lithium 0.7.8
	- minecraft 1.18.1
	- modmenu 3.0.1
	- mousetweaks 2.22
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- pride 1.1.0+1.17 via lambdynlights
	- sodium 0.4.0-alpha6+build.14
	- sodium-extra 0.3.8
	- spruceui 3.3.0+1.17 via lambdynlights
info: [15:55:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/user/AppData/Roaming/.minecraft/libraries/java/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
info: [15:55:07] [main/INFO]: Compatibility level set to JAVA_17
info: [15:55:07] [main/INFO]: Loaded configuration file for Lithium: 102 options available, 0 override(s) found
info: [15:55:07] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
info: [15:55:07] [main/INFO]: Loaded configuration file for Sodium Extra: 17 options available, 0 override(s) found
info: [15:55:08] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
info: [15:55:08] [main/WARN]: Error loading class: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen (java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen)
info: [15:55:08] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
error: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
info: [15:55:09] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) [rust-extension-1.0.7.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[minecraft-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 7 more
Caused by: java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues. As a temporary workaround you can enable "populateNeighborTable" in the FerriteCore config
	at malte0811.ferritecore.fastmap.table.CrashNeighborTable.crashOnAccess(CrashNeighborTable.java:101) ~[ferritecore-4.0.0-fabric.temp.jar:?]
	at malte0811.ferritecore.fastmap.table.CrashNeighborTable.rowKeySet(CrashNeighborTable.java:77) ~[ferritecore-4.0.0-fabric.temp.jar:?]
	at me.jellysquid.mods.lithium.common.state.FastImmutableTable.<init>(FastImmutableTable.java:36) ~[lithium-fabric-mc1.18.1-0.7.8.temp.jar:?]
	at net.minecraft.class_2688.handler$bfk000$postCreateWithTable(class_2688.java:1028) ~[client-intermediary.jar:?]
	at net.minecraft.class_2688.method_28496(class_2688.java:552) ~[client-intermediary.jar:?]
	at net.minecraft.class_2689.<init>(class_2689.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_2689$class_2690.method_11668(class_2689.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.<init>(class_2248.java:182) ~[client-intermediary.jar:?]
	at net.minecraft.class_2189.<init>(class_2189.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[minecraft-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 7 more
error: [2022-03-27T20:55:09Z INFO  rust_launcher::start::bindings] launch stalled

Tried turning off starlight: Yes

**Comment by malte0811** [comment]
Update FerriteCore, this is fixed in one of the newer builds.

**Comment by kispintyi** [comment]
I accidentally and wrongfully mentioned my issue here, please disregard it!
