### ISSUE TITLE
Crash with Hydrogen & Adorn

### ISSUE THREAD

**Issue by NebelNidas** [malte0811/FerriteCore#7]
FerriteCore + Adorn works fine, but adding Hydrogen on top will result in a crash.

**Mods:**
- [Adorn](https://www.curseforge.com/minecraft/mc-mods/adorn) 1.13.0+1.16.5
- [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) 0.31.0+1.16
- [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin) 1.4.21+build.1
- [Ferritecore](https://www.curseforge.com/minecraft/mc-mods/ferritecore) 2.0.3
- [Hydrogen](https://www.modrinth.com/mod/hydrogen) 0.2

**Crash log:**
````
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 01.03.21, 12:07
Description: Tesselating block in world - Indigo Renderer

java.lang.IllegalArgumentException: Cannot get property class_2754{name=front, clazz=class juuxel.adorn.block.property.FrontConnection, values=[NONE, LEFT, RIGHT]} as it does not exist in Block{adorn:oak_kitchen_sink}
	at net.minecraft.class_2688.method_11654(class_2688.java:95)
	at malte0811.ferritecore.impl.PropertyValueConditionImpl.lambda$null$1(PropertyValueConditionImpl.java:82)
	at malte0811.ferritecore.util.PredicateHelper.lambda$and$0(PredicateHelper.java:39)
	at net.minecraft.class_1095.method_4707(class_1095.java:56)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:91)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:60)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
	at net.minecraft.class_846$class_851$class_4578.redirect$zbk000$hookChunkBuildTesselate(class_846.java:711)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:512)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:434)
	at net.minecraft.class_846.method_22757(class_846.java:136)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:95)
	at malte0811.ferritecore.impl.PropertyValueConditionImpl.lambda$null$1(PropertyValueConditionImpl.java:82)
	at malte0811.ferritecore.util.PredicateHelper.lambda$and$0(PredicateHelper.java:39)
	at net.minecraft.class_1095.method_4707(class_1095.java:56)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:91)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:60)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)

-- Block being tesselated --
Details:
	Block: Block{adorn:oak_kitchen_sink}[waterlogged=true,facing=east,front=none]
	Block location: World: (-199,61,-269), Chunk: (at 9,3,3 in -13,-17; contains blocks -208,0,-272 to -193,255,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)

-- Affected level --
Details:
	All players: 1 total; [class_746['player_name'/402, l='ClientLevel', x=-228.62, y=69.00, z=-205.89]]
	Chunk stats: Client Chunk Cache: 2025, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-222,69,-197), Chunk: (at 2,4,11 in -14,-13; contains blocks -224,0,-208 to -209,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 49269467 game time, 30288705 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_846.method_22755(class_846.java:140)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.10, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 3508940952 bytes (3346 MB) / 4086300672 bytes (3897 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 4 total; -Xmx4G -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		fabric: Fabric API 0.31.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		ferritecore: FerriteCore 2.0.3
		hydrogen: Hydrogen 0.2
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 11
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		minecraft: Minecraft 1.16.5
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, programer_art
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
```

**Comment by malte0811** [comment]
This is essentially the same issue as CaffeineMC/hydrogen-fabric#19. You can fix it by disabling `cacheMultipartPredicates` (and `multipartDeduplication`) for now, but at that point you're not getting all that much from FC any more (`replaceNeighborLookup` and `bakedQuadDeduplication` are implicitly disabled by H). I can look into "fixing" it on my side, but in my opinion this should be fixed in H.

**Comment by NebelNidas** [comment]
Just weird that Adorn + Hydrogen itself works, too, it only crashes when having both Hydrogen **and** FerriteCore 🤔

**Comment by DragonEggBedrockBreaking** [comment]
> Just weird that Adorn + Hydrogen itself works too, it only crashes when having **both** Hydrogen **and** FerriteCore 🤔

Wait, are Hydrogen and FerriteCore compatible? I didn't know...

**Comment by LucilleTea** [comment]
This error also affects Tech Reborn, again only when both Hydrogen and FerriteCore are used. The game still starts rather than crashing, but the error spam in startup makes me think it wouldn't work very well.
Using Hydrogen with this PR https://github.com/CaffeineMC/hydrogen-fabric/pull/22 does fix the problem, so it seems it is on our side as you said.
