### ISSUE TITLE
Odd error net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: unknown:private/malte0811/ferritecore/impl/deduplicator$1

### ISSUE THREAD

**Issue by lospejos** [malte0811/FerriteCore#87]
Installed mods:
```
qfapi-4.0.0-beta.4_qsl-3.0.0-beta.7_fapi-0.58.5_mc-1.19.1
architectury-6.0.35-fabric
cloth-config-8.0.75-fabric
modmenu-4.0.5
notenoughcrashes-4.1.6+1.19-fabric
RoughlyEnoughItems-9.1.520
ferritecore-5.0.0-fabric
```

Got error on starting:

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2022-08-05 15:28:25
Description: Initializing game

net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: unknown:private/malte0811/ferritecore/impl/deduplicator$1
	at Not Enough Crashes deobfuscated stack trace.(1.19.1+build.4)
	at net.minecraft.util.Identifier.<init>(Identifier:41)
	at net.minecraft.util.Identifier.<init>(Identifier:50)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.sort(ResourceLoaderImpl.java:184)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.sort(ResourceLoaderImpl.java:107)
	at net.minecraft.resource.ReloadableResourceManagerImpl.handler$zdn000$reload(ReloadableResourceManagerImpl:559)
	at net.minecraft.resource.ReloadableResourceManagerImpl.reload(ReloadableResourceManagerImpl:47)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:647)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

```

I'm not sure is it a `Ferrit Core` mod or `Quilted Fabric` mod or even `Minecraft` issue. Sorry if my issue is created in a wrong repository

Thanks.

**Comment by lospejos** [comment]
I've also tested it using plugins:
```
fabric-api-0.58.5+1.19.1
ferritecore-5.0.0-fabric
modmenu-4.0.5
```
e.g. pure `Fabric API` instead of `Quilted Fabric API` and it works fine.

It looks like it may be a bug in a `Quilted API` mod loader.

**Comment by LambdAurora** [comment]
While this crash is a bug with Quilted Fabric API it highlights the lack of use of IdentifiableResourceReloadListener which can be an issue for other mods as it means the resource reloader isn't named, meaning if someone is trying to execute a resource reloader before or after (explicitly) yours they can't.

**Comment by lospejos** [comment]
I've also tried to test this combination of mods:
```
ferritecore-5.0.0-fabric
modmenu-4.0.5
notenoughcrashes-4.1.8+1.19.1-fabric
qfapi-4.0.0-beta.4_qsl-3.0.0-beta.7_fapi-0.58.5_mc-1.19.1
```
(updated `Not Enough Crashes` to a most recent `notenoughcrashes-4.1.8+1.19.1-fabric` comparing with previous test).

Crash dump looks like:
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2022-08-05 17:56:21
Description: Initializing game

net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: unknown:private/malte0811/ferritecore/impl/deduplicator$1
	at Not Enough Crashes deobfuscated stack trace.(1.19.1+build.4)
	at net.minecraft.util.Identifier.<init>(Identifier:41)
	at net.minecraft.util.Identifier.<init>(Identifier:50)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.sort(ResourceLoaderImpl.java:184)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.sort(ResourceLoaderImpl.java:107)
	at net.minecraft.resource.ReloadableResourceManagerImpl.handler$zdf000$reload(ReloadableResourceManagerImpl:559)
	at net.minecraft.resource.ReloadableResourceManagerImpl.reload(ReloadableResourceManagerImpl:47)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:647)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2960.<init>(class_2960.java:41)
	at net.minecraft.class_2960.<init>(class_2960.java:50)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.sort(ResourceLoaderImpl.java:184)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.sort(ResourceLoaderImpl.java:107)
	at net.minecraft.class_3304.handler$zdf000$reload(class_3304.java:559)
	at net.minecraft.class_3304.method_18232(class_3304.java:47)
	at net.minecraft.class_310.<init>(class_310.java:647)
...
```

**Comment by lospejos** [comment]
Closing this issue as this bug was fixed in `Quilted Fabric API`.
