### ISSUE TITLE
Crashes on 1.19.3 / 22w43a

### ISSUE THREAD

**Issue by SolDev69** [malte0811/FerriteCore#98]
```
[12:26:50] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) ~[NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:20) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:107) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:333) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[minecraft-22w43a-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-22w43a-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 11 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.lang.Class.getDeclaredField(Class.java:2602) ~[?:?]
	at malte0811.ferritecore.impl.BlockStateCacheImpl.lambda$static$1(BlockStateCacheImpl.java:36) ~[ferritecore-5.0.0-fabric.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar:?]
	at malte0811.ferritecore.impl.BlockStateCacheImpl.deduplicateCachePre(BlockStateCacheImpl.java:56) ~[ferritecore-5.0.0-fabric.jar:?]
	at net.minecraft.class_4970$class_4971.handler$znp000$cacheStateHead(class_4970.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:20) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:107) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:333) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[minecraft-22w43a-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-22w43a-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 11 more```

**Comment by malte0811** [comment]
I don't port to snapshots (sorry!), but it's good to know that 1.19.3 will require at least some changes to FC once it's fully released.
